# Generated by Django 3.1.2 on 2020-10-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='hours',
            new_name='number_of_songs',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='hours',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.group'),
        ),
        migrations.AlterField(
            model_name='clips',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.clips'),
        ),
    ]
