# Generated by Django 3.1.2 on 2020-10-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0002_auto_20201019_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='clips',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
