# Generated by Django 3.1.2 on 2020-10-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0003_auto_20201025_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.RenameField(
            model_name='clips',
            old_name='hours',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='hours',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='song',
            name='desc',
        ),
    ]
