# Generated by Django 3.1.2 on 2020-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0004_auto_20201025_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='time',
            field=models.TimeField(),
        ),
    ]
