# Generated by Django 3.1.2 on 2020-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0005_auto_20201025_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='age',
            field=models.DateField(auto_now=True),
        ),
    ]
