# Generated by Django 3.1.2 on 2020-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0006_auto_20201025_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
